# Generated by Django 4.2.30 on 2026-06-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('task_name', models.CharField(max_length=200)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('work_date', models.DateField()),
            ],
        ),
    ]
