# Generated by Django 4.2.30 on 2026-06-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0003_employeetask_delete_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetask',
            name='task_name',
            field=models.CharField(max_length=255),
        ),
    ]
