# Generated by Django 4.2.30 on 2026-06-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0004_alter_employeetask_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
