# Generated by Django 4.2.30 on 2026-06-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0005_employeetask_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetask',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employeetask',
            name='hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employeetask',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
