# Generated by Django 4.2.30 on 2026-06-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0006_employeetask_is_default_alter_employeetask_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetask',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
