# Generated by Django 4.2.30 on 2026-06-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0007_alter_employeetask_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetask',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeetask',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='employeetask',
            name='hours',
            field=models.FloatField(default=0),
        ),
    ]
